version: "3.7"
services:
  cybercom_mongo:
    image: mongo
    command: --sslMode requireSSL --sslPEMKeyFile /ssl/server/mongodb.pem --sslCAFile /ssl/testca/cacert.pem --auth
    restart: unless-stopped
    env_file:
      - dc_config/cybercom_config.env
    expose:
      - 27017
    volumes:
      - cc_mongo:/data/db
      - ./dc_config/ssl/backend:/ssl
  cybercom_rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    env_file:
      - dc_config/cybercom_config.env
    volumes:
      - ./dc_config/ssl/backend:/ssl
    expose:
      - 5671
  cybercom_memcache:
    image: memcached
    restart: unless-stopped
    env_file:
      - dc_config/cybercom_config.env
    expose:
      - 11211
    ports:
      - 11211:11211
  cybercom_celery:
    image: celeryapp
    restart: unless-stopped
    build: dc_config/images/celery
    volumes:
      - ./dc_config/ssl/backend:/ssl
    env_file:
      - dc_config/cybercom_config.env
    depends_on:
      - cybercom_mongo
      - cybercom_rabbitmq
  cybercom_api:
    image: api:latest
    restart: unless-stopped
    build: .
    env_file:
      - dc_config/cybercom_config.env
    volumes:
      - ./dc_config/ssl/backend:/ssl
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - cybercom_mongo
      - cybercom_rabbitmq
volumes:
  cc_mongo:
    external: true
