#!/bin/bash

#generate keys for nginx
# SSL has not been configured for nginx - to force generation of keys, uncomment the following lines:
#docker run -it --rm --name testetag_openssl \
#  -v $PWD/ssl/nginx:/sslnginx:z \
#  cybercom/openssl ./sslnginx/generate

#generate keys for message broker, mongodb, and clients
docker run -it --rm \
  -v $PWD/ssl/backend:/ssl \
  -e "CA_EXPIRE=3650" \
  -e "KEY_SECRET=testing" \
  cybercom/openssl ./ssl/generate

